# Generated by Django 3.1.4 on 2021-02-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedTypes',
            fields=[
                ('bed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bed_available', models.IntegerField()),
                ('bed_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BedSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.PositiveIntegerField()),
                ('free_or_occupy', models.BooleanField(default=False)),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_mobile', models.CharField(max_length=10)),
                ('checkout', models.BooleanField(default=False)),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidApp.bedtypes')),
            ],
        ),
    ]
